### ISSUE TITLE
Create CI/CD Pipelines with GitHub Actions

### ISSUE THREAD

**Issue by kishieel** [kishieel/men3-stack#7]
Pull request 

- [x] lint
- [x] codeql
- [x] unit tests
- [x] e2e tests

Push to master

- [x] build containers
- [x] deploy to staging

Push tag to master (blocked by #3) 

- [x] build containers
- [x] deploy to production

Apps:
- [x] backend (blocked by #3)
- [x] frontend (blocked by #5)
- [ ] expo (blocked by #6)

Each environment should be possible to easily disable
- [x] add variable ENABLED and use it in github actions
